FROM mcr.microsoft.com/vscode/devcontainers/python:3.10

RUN curl -sSL https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64 > /bin/hadolint && \
    chmod +x /bin/hadolint
